package be.howest.ti.monopoly.logic.implementation;

public enum CommunityChests {
    ADV_GO,
    REC_BANK_ERR,
    PAY_DOCTOR_FEE,
    REC_SOLD_STOCK,
    GET_JAIL_CARD,
    GO_JAIL,
    REC_HOLIDAY,
    REC_TAX,
    REC_BIRTHDAY,
    REC_INSURANCE,
    PAY_HOSPITAL,
    PAY_SCHOOL,
    REC_CONSULTANCY,
    PAY_REPAIRS,
    REC_PRIZE,
    REC_DELFINO, REC_BANK_OWES, REC_KOOPALING, PAY_BOO, PAY_STAR, REC_FRUIT, REC_ROSALINA, REC_INHERIT
}
